name: James Hensman
markdown: kramdown
port: 4000
highlighter: pygments
gems:
  - "jekyll/scholar"
scholar:
  style: apa
  locale: en
 
  sort_by: year
  order: descending
  bibliography_list_tag: ul
 
  source: _bibliography
  repository: pdf
  bibliography: references
 
  replace_strings: true
 
  details_dir:    bibliography
  details_layout: bibtex.html
  details_link:   Details
 
  query: "@*"
